repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pre-commit
        name: pre-commit stuff in tasks.py
        language: system
        entry: inv check-black
        pass_filenames: false
